# Generated by Django 4.0 on 2021-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetrysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_name', models.CharField(max_length=128)),
                ('poem', models.CharField(max_length=8192)),
                ('tags', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Poem',
        ),
    ]
